# Generated by Django 5.0.6 on 2024-06-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencypair',
            name='symbol',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='currencypair',
            name='type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='currencypair',
            name='name',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
